#!/usr/bin/env python3
"""
Phase 4 — Other Exams index (SSC CHSL, CPO, Stenographer, RRB, etc.)
=====================================================================

These 142 tests existed in the dataset but had NO browsable UI in the
original app at all (verified: `OTHER_EXAMS_COUNT` was defined but never
rendered anywhere). This script classifies them by actual exam type —
using the `exam` field where set, and falling back to title-text keyword
matching where it isn't (which correctly identifies ~94 more of them) —
and writes src/data/otherExams.js for a new "Other Exams" tab to consume.

Usage:
    python3 scripts/phase4_other_exams_index.py
"""

import json
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parent.parent if (Path(__file__).parent.name == "scripts") else Path(".")
OTHER_EXAMS_DIR = REPO_ROOT / "public" / "tests-organized" / "tests" / "full" / "other-exams"
OUT_JS = REPO_ROOT / "src" / "data" / "otherExams.js"

# Order matters: more specific keywords first (e.g. "SELECTION POST" before
# a bare "POST" would ever be added).
KEYWORD_RULES = [
    ("SSC CHSL", ["CHSL"]),
    ("SSC CPO", ["CPO"]),
    ("SSC Stenographer", ["STENO"]),
    ("SSC Selection Post", ["SELECTION POST"]),
    ("SSC GD", [" GD ", " GD-", "GD 20"]),
    ("SSC JE", [" JE ", " JE-", "JE 20"]),
    ("RRB", ["NTPC", "RRB"]),
    ("IB", ["IB SA", "IB ACIO", "ACIO"]),
    ("RPF", ["RPF"]),
]


def classify(title: str, exam_field: str):
    if exam_field:
        return exam_field
    t = f" {(title or '').upper()} "
    for label, keywords in KEYWORD_RULES:
        if any(kw in t for kw in keywords):
            return label
    return "Unspecified"


def main():
    if not OTHER_EXAMS_DIR.exists():
        print(f"ERROR: {OTHER_EXAMS_DIR} not found.")
        return

    files = list(OTHER_EXAMS_DIR.rglob("*.json"))
    print(f"Found {len(files)} other-exam files.")

    by_exam = defaultdict(list)
    for f in files:
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  SKIP: {f} ({e})")
            continue
        if not isinstance(data, dict) or "title" not in data:
            continue

        title = data.get("displayTitle") or data.get("title")
        exam_type = classify(title, data.get("exam"))
        rel_path = f.relative_to(REPO_ROOT / "public" / "tests-organized" / "tests").as_posix()

        by_exam[exam_type].append({
            "id": f.stem,  # MUST match testCards.js scheme (filename-based), not the JSON's internal id field
            "title": title,
            "path": rel_path,
            "questionCount": data.get("questionCount"),
            "duration": data.get("duration"),
            "provider": data.get("provider"),
            "year": data.get("year"),
        })

    for exam_type, entries in by_exam.items():
        entries.sort(key=lambda e: e["title"] or "")

    # "Unspecified" sorted to the end regardless of count, so it doesn't
    # dominate the tab order just because it has more items than a rare category.
    exam_order = sorted(
        [k for k in by_exam if k != "Unspecified"],
        key=lambda k: -len(by_exam[k])
    )
    if "Unspecified" in by_exam:
        exam_order.append("Unspecified")

    lines = [
        "// AUTO-GENERATED by scripts/phase4_other_exams_index.py — do not hand-edit.",
        "// Other Exams (SSC CHSL, CPO, Stenographer, RRB, IB, RPF, etc.) grouped",
        "// by exam type. These 142 tests previously had no browsable UI at all.",
        "",
        "export const OTHER_EXAMS_BY_TYPE = {",
    ]
    for exam_type in exam_order:
        lines.append(f'  "{exam_type}": [')
        for e in by_exam[exam_type]:
            lines.append("    " + json.dumps(e, ensure_ascii=False) + ",")
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    lines.append("export const OTHER_EXAM_TYPES = " + json.dumps(exam_order) + ";")
    lines.append("")

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text("\n".join(lines), encoding="utf-8")

    print("\nBreakdown:")
    for exam_type in exam_order:
        print(f"  {exam_type}: {len(by_exam[exam_type])}")
    print(f"\nWrote: {OUT_JS}")


if __name__ == "__main__":
    main()
